server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fodor-marcell/estore-config
          default-label: master
          search-paths: '{application}'

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  server:
    port: 8888
    address: 0.0.0.0