spring:
  datasource:
    url: jdbc:postgresql://db:5432/estore
    username: postgres
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.fdr.estore: DEBUG

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh